import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // ✅ use this path
import "./globals.css";

// Load the Poppins font
const poppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}> {/* ✅ this is also correct */}
        {children}
      </body>
    </html>
  );
}
